name: Python Script Workflow

on:
  workflow_dispatch:
    inputs:
      patch_number:
        description: 'Enter the patch number'
        required: true

jobs:
  run_script:
    runs-on: windows-latest  # Use a Windows runner
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify your desired Python version
        
    - name: Install dependencies
      run: |
        pip install pywin32  # If pywin32 is needed
        
    - name: Run Python Script
      shell: cmd
      run: |
        python -c "import os; os.system('python C:\\Users\\tejas\\OneDrive\\Desktop\\khr_prod.py')"  # Replace with the actual path

      env:
        SOURCE_DIR: C:\\Users\\tejas\\OneDrive\\Desktop\\My Documents\\bin  # Directly specifying the source directory
        PATCH_NUMBER: ${{ github.event.inputs.patch_number }}
